name: dakowa_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  percent_indicator: ^3.0.1
  flutterwave: ^0.0.2
  youtube_player_iframe: ^2.0.0
  dio: ^4.0.0
  flutter_easyloading: ^3.0.0
  url_launcher: ^6.0.3
  intl: any
  get: ^4.1.4
  jiffy: any
  shared_preferences: ^2.0.5
  qr_flutter: ^4.0.0
  provider: ^5.0.0
  cached_network_image: ^3.0.0
  flutter_paystack: ^1.0.5+1
  clipboard: ^0.1.3
  share_plus: ^2.1.2
  image_picker: ^0.8.0+1
  path: ^1.8.0
  universal_html: ^2.0.8
  screenshot: ^1.2.1
  expandable_bottom_sheet: ^1.0.0+2
  firebase_messaging: ^10.0.2
  firebase_core: ^1.3.0
  flutter_local_notifications: ^6.0.0
  image_gallery_saver: '^1.6.9'
  permission_handler: ^8.1.1
  assets_audio_player: ^3.0.3+1
  flutter_native_splash: ^1.2.0
  rate_my_app: ^1.1.0+1
  in_app_update: ^2.0.0
  simple_url_preview: ^3.0.1
  package_info_plus: ^1.0.3
  linkify: ^4.0.0
  firebase_in_app_messaging: ^0.5.0+6
  firebase_dynamic_links: ^2.0.6
  flutter_easyrefresh: ^2.2.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/thealiento.png
    - assets/images/goals_icon.png
    - assets/images/signup.png
    - assets/images/frontimage.png
    - assets/images/people.webp
    - assets/images/lesson.webp
    - assets/images/gold.png
    - assets/images/supporters.png
    - assets/images/supports.png
    - assets/images/custom_icon.png
    - assets/images/main_logo.png
    - assets/images/mainlogo_white.png
    - assets/images/about.jpg
    - assets/audio/swiftly-610.m4r
    - assets/audio/swiftly-610.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KiwiRegular
      fonts:
        - asset: assets/fonts/KiwiMaru-Regular.ttf
    - family: KiwiMedium
      fonts:
        - asset: assets/fonts/KiwiMaru-Medium.ttf
    - family: KiwiLight
      fonts:
        - asset: assets/fonts/KiwiMaru-Light.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
